#Don't print a new line at the start of the prompt
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"

# Use custom format
 format = """
 [┌───────────────────>](red bold)
 [│](red bold)$directory$rust$package
 [└─>](red bold)$shlvl """

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

format = "$all"

[aws]
disabled = true
[cmake]
disabled = true
[cmd_duration]
format = '\[[⏱ $duration ]($style)\]'

[cobol]
disabled = true
[conda]
disabled = true
[crystal]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[gcloud]
disabled = true
[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
disabled = true
[helm]
disabled = true
[hg_branch]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[kubernetes]
disabled = true
[lua]
disabled = true
[memory_usage]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true

[ocaml]
disabled = true
[openstack]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[pulumi]
disabled = true
[purescript]
disabled = true
[python]
disabled = true
[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[sudo]
format = '\[[as $symbol]\]'

[swift]
disabled = true

[terraform]
disabled = true

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
