#!/bin/zsh

[ -f "$HOME/.config/env" ] && source "$HOME/.config/env"

if [ -e /home/server/.nix-profile/etc/profile.d/nix.sh ]; then . /home/server/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
